name: jaguar_retrofit_gen
description: Generator for jaguar_retrofit, a Retrofit inspired declarative HTTP client.
version: 2.8.10
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/Jaguar-dart/client

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  analyzer: ^0.36.0
  build: ^1.1.4
  logging: ^0.11.0
  source_gen: ^0.9.0
  meta: ^1.1.5
  jaguar_resty: ^2.10.14
  jaguar_retrofit: ^2.8.8

dev_dependencies:
  pedenatic:
  test: ^1.3.0
  build_runner: ^1.5.0
  collection: ^1.14.10
  path: ^1.6.2

#dependency_overrides:
#  jaguar_retrofit:
#    path: ../retrofit