name: jaguar_retrofit
description: Retrofit inspired declarative HTTP client for Dart.
version: 2.5.4
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/Jaguar-dart/client

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  jaguar_serializer: ^2.2.2
  http: ^0.11.3
  meta: ^1.1.5
  jaguar_resty: ^2.8.4

dev_dependencies:
  test: ^1.3.0
  jaguar_serializer_cli: ^2.2.0
  build_runner:
  jaguar: ^2.2.20
  jaguar_retrofit_gen:
    path: ../retrofit_gen